### ISSUE TITLE
Compiled Vs Interpreted languages

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guide-articles#62]

**Comment by highlanderkev** [comment]
A compiled language refers to a programming language that requires compilation prior to running. Typically, compilation refers to the process of inputting a program, via source file(s), and outputting some type of executable file/program. Most commonly the outputted executable is system specific machine code which can only be run on a particular type of machine with a specific instruction set (ex. Intel's IA-32 instruction set). This process of compilation is not to be confused with the Java (javac) compilation process which first compiles the program into intermediate Java byte code which can then be run/compiled using Java's Just-in-time compiler which re-compiles the intermediate byte code into a machine specific executable.  

An interpreted language refers to a programming language that does not require prior compilation before being run but can be run via the use of an interpreter. An interpreter is most commonly an external executable program that dynamically reads a source file(s) or input as source code and runs it as instructions on the specific machine hosting the interpreter. This usually involves intermediate steps that dynamically convert the source code into machine executable code and thus shares similarity with the process of compilation (similar steps involved) but from a high level the difference is that interpretation doesn't output an executable for you to run at a later date/time, instead executing automatically. 

The differences and similarities between compilation and interpretation is muddled when it comes to programming languages because many languages exhibit characteristics of both besides the aforementioned Java Compiler.
