### ISSUE TITLE
What is garbage collection?

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guide-articles#67]

**Comment by highlanderkev** [comment]
Garbage collection is the process by which a memory managed programming language or system collects unused allocated memory. Generally, this means that when a program is done using memory, as in the case of a stored variable, it's space allocation will be freed to be used for other variables not already allocated space in memory. Typically, garbage collection occurs in dynamic memory management languages or runtime systems where the need for manually allocating memory (via calls like malloc and free) are no longer needed/required. 

When a program runs, variables, functions and objects are allocated memory locations (typically a pointer to that specific location in memory) and space (size of required memory, for example in C on a x86 system an int data type requires 32 bits). Once those variables are no longer used or needed by the running program, they are marked for garbage collection which means they can be freed from memory or otherwise marked as unused memory locations.

**Comment by brianamarie** [comment]
## What is Garbage Collection? 

#### Garbage collection 
- Garbage collection sounds like what it is
- Garbage collection is when your computer collects unused memory
- Generally, this means that when a program is done using memory, that allocation will be freed to be used for other things. 
-  Happens behind the scenes 

#### When does this happen? 
- When a program runs, variables, functions and objects are allocated memory locations
  - typically a pointer to that specific location in memory
  - space (size of required memory, for example in C on a x86 system an int data type requires 32 bits). 
- Once those variables are no longer used or needed by the running program, they are marked for garbage collection
