### ISSUE TITLE
What is Statistics?

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guide-articles#88]
From: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5285
# What is Statistics

A hike defining what statistics is.

"Statistics is the study of data including how you collect, organize, transform, analyze, and present it"

Example statistic problems, bioinformatics, data aggregation, etc.

How to make sense of your data, someone can't be 20 meters tall etc.

Mention common terms and reference that they'll be introduced in other hikes.

1) Is statistics the study of numbers? F
2) Is data presentation a part of statistics? T
3) Do statisticians clean data? T

**Comment by matthras** [comment]
"*Statistics is the study of data including how it is collected, organised, transformed, analysed, and presented.*

*Statistical problems can be found across a variety of industries: Facebook and Google aim to better understand your internet browsing habits for targeted marketing purposes; bioinformaticians use data to build models that allow them to understand how cancer mutates and how DNA evolves; when you look through the analytics of that website you've just built, you'll be able to identify your visitors' browsing behaviour.*

*An understanding of statistics will lead to an overall understanding of how data is interpreted and reported. Are you sure that pregnancy test is not displaying a false positive?  Do students really hate studying, or did the survey target the disillusioned and underperforming students? How significant is that 80% increase of chance of developing cancer? Because that number tells you nothing unless you know the initial risk.*

*Statistics go hand-in-hand with probability, and throughout these hikes we will cover a number of distributions as well as concepts that when used correctly, can be powerful tools that can provide insightful information for both analyst and layman."*

I imagine some wording/phrasing can be fixed, but what I'm more curious about at the moment is how you'd like me to tailor this hike (and future statistics-related hikes) towards FreeCodeCamp-related topics. Looking forward to all your feedback :)

**Comment by SEGrooms** [comment]
@matthras In the last paragraph, maybe explain a distinction between statistics and probability. Other than that it looks great! :+1:

**Comment by matthras** [comment]
Draft video here https://www.youtube.com/watch?v=ssJ8z9BZgG4

Still some things to fix up (e.g. laggy frames when displaying the data bit), but any other feedback is welcome.

**Comment by atjonathan** [comment]
@matthras, awesome, please make a pull request to this repo with your script in the appropriate folder.

**Comment by brianamarie** [comment]
@matthras, I really enjoyed your video!!! 😻  I like the way you present, your voice is engaging to listen to. 😄 

What are your thoughts of splitting this content up into smaller videos? Maybe something like:
Statistics: What are they and why do they matter? (1 minute or so) 
Statistics: Answering questions
Statistics: How to gather data
Statistics: Visualizing data/using JS tools

What do you think? 
cc/ @atjonathan @QuincyLarson

**Comment by atjonathan** [comment]
Yeah defiantly @brianamarie that's a good point :+1:

**Comment by matthras** [comment]
I agree that splitting up the overall process into separate topics for each of the sections is a great idea - the only slight problem is that I'm currently drawing a blank on some of the topics. Nothing a bit of research/googling can't do, though. 

Guess I'll update the Stats/Probability thread when I get another breather.
